//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:45:41 PM IST 
//


package com.cipherdot.aca.model.BM01;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BondMgmtTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BondMgmtTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MvmtNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TdocNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShpAWBNum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PcId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BondLoc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Tmstmp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NumOfPcs">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Evt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeclaredShptWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShpSts" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Shpdescrp" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="70"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UbdDestSrvaCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UbdDestLocCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BondMgmtTyp", propOrder = {

})
public class BondMgmtTyp {

    @XmlElement(name = "MvmtNo")
    protected String mvmtNo;
    @XmlElement(name = "TdocNo", required = true)
    protected String tdocNo;
    @XmlElement(name = "ShpAWBNum", required = true)
    protected String shpAWBNum;
    @XmlElement(name = "PcId", required = true)
    protected String pcId;
    @XmlElement(name = "BondLoc")
    protected String bondLoc;
    @XmlElement(name = "Tmstmp", required = true)
    protected String tmstmp;
    @XmlElement(name = "NumOfPcs", required = true)
    protected BigInteger numOfPcs;
    @XmlElement(name = "Evt", required = true)
    protected String evt;
    @XmlElement(name = "DeclaredShptWeight")
    protected BigDecimal declaredShptWeight;
    @XmlElement(name = "ShpSts")
    protected String shpSts;
    @XmlElement(name = "Shpdescrp")
    protected String shpdescrp;
    @XmlElement(name = "UbdDestSrvaCd")
    protected String ubdDestSrvaCd;
    @XmlElement(name = "UbdDestLocCd")
    protected String ubdDestLocCd;

    /**
     * Gets the value of the mvmtNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMvmtNo() {
        return mvmtNo;
    }

    /**
     * Sets the value of the mvmtNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMvmtNo(String value) {
        this.mvmtNo = value;
    }

    /**
     * Gets the value of the tdocNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdocNo() {
        return tdocNo;
    }

    /**
     * Sets the value of the tdocNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdocNo(String value) {
        this.tdocNo = value;
    }

    /**
     * Gets the value of the shpAWBNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShpAWBNum() {
        return shpAWBNum;
    }

    /**
     * Sets the value of the shpAWBNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShpAWBNum(String value) {
        this.shpAWBNum = value;
    }

    /**
     * Gets the value of the pcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcId() {
        return pcId;
    }

    /**
     * Sets the value of the pcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcId(String value) {
        this.pcId = value;
    }

    /**
     * Gets the value of the bondLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondLoc() {
        return bondLoc;
    }

    /**
     * Sets the value of the bondLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondLoc(String value) {
        this.bondLoc = value;
    }

    /**
     * Gets the value of the tmstmp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmstmp() {
        return tmstmp;
    }

    /**
     * Sets the value of the tmstmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmstmp(String value) {
        this.tmstmp = value;
    }

    /**
     * Gets the value of the numOfPcs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumOfPcs() {
        return numOfPcs;
    }

    /**
     * Sets the value of the numOfPcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumOfPcs(BigInteger value) {
        this.numOfPcs = value;
    }

    /**
     * Gets the value of the evt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvt() {
        return evt;
    }

    /**
     * Sets the value of the evt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvt(String value) {
        this.evt = value;
    }

    /**
     * Gets the value of the declaredShptWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeclaredShptWeight() {
        return declaredShptWeight;
    }

    /**
     * Sets the value of the declaredShptWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeclaredShptWeight(BigDecimal value) {
        this.declaredShptWeight = value;
    }

    /**
     * Gets the value of the shpSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShpSts() {
        return shpSts;
    }

    /**
     * Sets the value of the shpSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShpSts(String value) {
        this.shpSts = value;
    }

    /**
     * Gets the value of the shpdescrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShpdescrp() {
        return shpdescrp;
    }

    /**
     * Sets the value of the shpdescrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShpdescrp(String value) {
        this.shpdescrp = value;
    }

    /**
     * Gets the value of the ubdDestSrvaCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUbdDestSrvaCd() {
        return ubdDestSrvaCd;
    }

    /**
     * Sets the value of the ubdDestSrvaCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUbdDestSrvaCd(String value) {
        this.ubdDestSrvaCd = value;
    }

    /**
     * Gets the value of the ubdDestLocCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUbdDestLocCd() {
        return ubdDestLocCd;
    }

    /**
     * Sets the value of the ubdDestLocCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUbdDestLocCd(String value) {
        this.ubdDestLocCd = value;
    }

}
