//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:45:41 PM IST 
//


package com.cipherdot.aca.model.BM01;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsgHdrTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgHdrTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MsgTyp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgMajVsn">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgMinVsn">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SrcMsgId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CrtnDm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="25"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LastProcessedDm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="25"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgOrgnatorAppl">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgGenAddr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgSeq" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="18"/>
 *               &lt;fractionDigits value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LastProcessedBy" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgRef" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgReqstor" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MsgReqstorAddr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgHdrTyp", propOrder = {

})
public class MsgHdrTyp {

    @XmlElement(name = "MsgTyp", required = true)
    protected String msgTyp;
    @XmlElement(name = "MsgMajVsn", required = true)
    protected BigInteger msgMajVsn;
    @XmlElement(name = "MsgMinVsn", required = true)
    protected BigInteger msgMinVsn;
    @XmlElement(name = "SrcMsgId")
    protected String srcMsgId;
    @XmlElement(name = "CrtnDm", required = true)
    protected String crtnDm;
    @XmlElement(name = "LastProcessedDm")
    protected String lastProcessedDm;
    @XmlElement(name = "MsgOrgnatorAppl", required = true)
    protected String msgOrgnatorAppl;
    @XmlElement(name = "MsgGenAddr")
    protected String msgGenAddr;
    @XmlElement(name = "MsgSeq")
    protected BigDecimal msgSeq;
    @XmlElement(name = "LastProcessedBy")
    protected String lastProcessedBy;
    @XmlElement(name = "MsgRef")
    protected String msgRef;
    @XmlElement(name = "MsgReqstor")
    protected String msgReqstor;
    @XmlElement(name = "MsgReqstorAddr")
    protected String msgReqstorAddr;

    /**
     * Gets the value of the msgTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgTyp() {
        return msgTyp;
    }

    /**
     * Sets the value of the msgTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgTyp(String value) {
        this.msgTyp = value;
    }

    /**
     * Gets the value of the msgMajVsn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMsgMajVsn() {
        return msgMajVsn;
    }

    /**
     * Sets the value of the msgMajVsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMsgMajVsn(BigInteger value) {
        this.msgMajVsn = value;
    }

    /**
     * Gets the value of the msgMinVsn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMsgMinVsn() {
        return msgMinVsn;
    }

    /**
     * Sets the value of the msgMinVsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMsgMinVsn(BigInteger value) {
        this.msgMinVsn = value;
    }

    /**
     * Gets the value of the srcMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcMsgId() {
        return srcMsgId;
    }

    /**
     * Sets the value of the srcMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcMsgId(String value) {
        this.srcMsgId = value;
    }

    /**
     * Gets the value of the crtnDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrtnDm() {
        return crtnDm;
    }

    /**
     * Sets the value of the crtnDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrtnDm(String value) {
        this.crtnDm = value;
    }

    /**
     * Gets the value of the lastProcessedDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastProcessedDm() {
        return lastProcessedDm;
    }

    /**
     * Sets the value of the lastProcessedDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastProcessedDm(String value) {
        this.lastProcessedDm = value;
    }

    /**
     * Gets the value of the msgOrgnatorAppl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgOrgnatorAppl() {
        return msgOrgnatorAppl;
    }

    /**
     * Sets the value of the msgOrgnatorAppl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgOrgnatorAppl(String value) {
        this.msgOrgnatorAppl = value;
    }

    /**
     * Gets the value of the msgGenAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgGenAddr() {
        return msgGenAddr;
    }

    /**
     * Sets the value of the msgGenAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgGenAddr(String value) {
        this.msgGenAddr = value;
    }

    /**
     * Gets the value of the msgSeq property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMsgSeq() {
        return msgSeq;
    }

    /**
     * Sets the value of the msgSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMsgSeq(BigDecimal value) {
        this.msgSeq = value;
    }

    /**
     * Gets the value of the lastProcessedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastProcessedBy() {
        return lastProcessedBy;
    }

    /**
     * Sets the value of the lastProcessedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastProcessedBy(String value) {
        this.lastProcessedBy = value;
    }

    /**
     * Gets the value of the msgRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgRef() {
        return msgRef;
    }

    /**
     * Sets the value of the msgRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgRef(String value) {
        this.msgRef = value;
    }

    /**
     * Gets the value of the msgReqstor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgReqstor() {
        return msgReqstor;
    }

    /**
     * Sets the value of the msgReqstor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgReqstor(String value) {
        this.msgReqstor = value;
    }

    /**
     * Gets the value of the msgReqstorAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgReqstorAddr() {
        return msgReqstorAddr;
    }

    /**
     * Sets the value of the msgReqstorAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgReqstorAddr(String value) {
        this.msgReqstorAddr = value;
    }

}
