//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:45:41 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dhl.com/ACA", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cipherdot.aca.model.BM01;
