//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:45:42 PM IST 
//


package com.cipherdot.aca.model.SU01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CstmTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CstmTyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ShpAWBNum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Tmstmp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClrFlg">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShpSts">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OrgnSrvaCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DestSrvaCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InBond" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InBondSrvaCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="InBondFcltyCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TdocNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PcId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CstmTyp", propOrder = {

})
public class CstmTyp {

    @XmlElement(name = "ShpAWBNum")
    protected String shpAWBNum;
    @XmlElement(name = "Tmstmp", required = true)
    protected String tmstmp;
    @XmlElement(name = "ClrFlg", required = true)
    protected String clrFlg;
    @XmlElement(name = "ShpSts", required = true)
    protected String shpSts;
    @XmlElement(name = "OrgnSrvaCd")
    protected String orgnSrvaCd;
    @XmlElement(name = "DestSrvaCd")
    protected String destSrvaCd;
    @XmlElement(name = "InBond")
    protected String inBond;
    @XmlElement(name = "InBondSrvaCd")
    protected String inBondSrvaCd;
    @XmlElement(name = "InBondFcltyCd")
    protected String inBondFcltyCd;
    @XmlElement(name = "TdocNo")
    protected String tdocNo;
    @XmlElement(name = "PcId")
    protected String pcId;

    /**
     * Gets the value of the shpAWBNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShpAWBNum() {
        return shpAWBNum;
    }

    /**
     * Sets the value of the shpAWBNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShpAWBNum(String value) {
        this.shpAWBNum = value;
    }

    /**
     * Gets the value of the tmstmp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTmstmp() {
        return tmstmp;
    }

    /**
     * Sets the value of the tmstmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTmstmp(String value) {
        this.tmstmp = value;
    }

    /**
     * Gets the value of the clrFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrFlg() {
        return clrFlg;
    }

    /**
     * Sets the value of the clrFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrFlg(String value) {
        this.clrFlg = value;
    }

    /**
     * Gets the value of the shpSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShpSts() {
        return shpSts;
    }

    /**
     * Sets the value of the shpSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShpSts(String value) {
        this.shpSts = value;
    }

    /**
     * Gets the value of the orgnSrvaCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnSrvaCd() {
        return orgnSrvaCd;
    }

    /**
     * Sets the value of the orgnSrvaCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnSrvaCd(String value) {
        this.orgnSrvaCd = value;
    }

    /**
     * Gets the value of the destSrvaCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestSrvaCd() {
        return destSrvaCd;
    }

    /**
     * Sets the value of the destSrvaCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestSrvaCd(String value) {
        this.destSrvaCd = value;
    }

    /**
     * Gets the value of the inBond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBond() {
        return inBond;
    }

    /**
     * Sets the value of the inBond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBond(String value) {
        this.inBond = value;
    }

    /**
     * Gets the value of the inBondSrvaCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBondSrvaCd() {
        return inBondSrvaCd;
    }

    /**
     * Sets the value of the inBondSrvaCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBondSrvaCd(String value) {
        this.inBondSrvaCd = value;
    }

    /**
     * Gets the value of the inBondFcltyCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBondFcltyCd() {
        return inBondFcltyCd;
    }

    /**
     * Sets the value of the inBondFcltyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBondFcltyCd(String value) {
        this.inBondFcltyCd = value;
    }

    /**
     * Gets the value of the tdocNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdocNo() {
        return tdocNo;
    }

    /**
     * Sets the value of the tdocNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdocNo(String value) {
        this.tdocNo = value;
    }

    /**
     * Gets the value of the pcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcId() {
        return pcId;
    }

    /**
     * Sets the value of the pcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcId(String value) {
        this.pcId = value;
    }

}
