//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:45:42 PM IST 
//


package com.cipherdot.aca.model.SU01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MsgHdr" type="{http://www.dhl.com/ACA}MsgHdrTyp"/>
 *         &lt;element name="CstmSts" type="{http://www.dhl.com/ACA}CstmTyp"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "MGMsg")
public class MGMsg {

    @XmlElement(name = "MsgHdr", required = true)
    protected MsgHdrTyp msgHdr;
    @XmlElement(name = "CstmSts", required = true)
    protected CstmTyp cstmSts;

    /**
     * Gets the value of the msgHdr property.
     * 
     * @return
     *     possible object is
     *     {@link MsgHdrTyp }
     *     
     */
    public MsgHdrTyp getMsgHdr() {
        return msgHdr;
    }

    /**
     * Sets the value of the msgHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgHdrTyp }
     *     
     */
    public void setMsgHdr(MsgHdrTyp value) {
        this.msgHdr = value;
    }

    /**
     * Gets the value of the cstmSts property.
     * 
     * @return
     *     possible object is
     *     {@link CstmTyp }
     *     
     */
    public CstmTyp getCstmSts() {
        return cstmSts;
    }

    /**
     * Sets the value of the cstmSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CstmTyp }
     *     
     */
    public void setCstmSts(CstmTyp value) {
        this.cstmSts = value;
    }

}
