//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 05:45:42 PM IST 
//


package com.cipherdot.aca.model.SU01;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cipherdot.aca.model.SU01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cipherdot.aca.model.SU01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MGMsg }
     * 
     */
    public MGMsg createMGMsg() {
        return new MGMsg();
    }

    /**
     * Create an instance of {@link MsgHdrTyp }
     * 
     */
    public MsgHdrTyp createMsgHdrTyp() {
        return new MsgHdrTyp();
    }

    /**
     * Create an instance of {@link CstmTyp }
     * 
     */
    public CstmTyp createCstmTyp() {
        return new CstmTyp();
    }

}
